# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Unlikenesses Blog
tagline:          ''
description:      ''
url:              http://unlikenesses.github.io
baseurl:          /

author:
  name:           
  url:          

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/unlikenesses/unlikenesses.github.io

# Gems
plugins: [jekyll-paginate]